assembler:	main.c aux_functions_main.c first_read.c second_read.c aux_functions_firstread.c aux_functions_secondread.c main.h aux_functions_main.h first_read.h aux_functions_firstread.h aux_functions_secondread.h second_read.h
		gcc -g -Wall -ansi -pedantic main.c aux_functions_main.c first_read.c second_read.c aux_functions_firstread.c aux_functions_secondread.c -o assembler

clean:	rm*~